"""unique account and 3th account

Revision ID: 817687f18082
Revises: 2e3b172b3f63
Create Date: 2024-06-10 18:47:13.009426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '817687f18082'
down_revision = '2e3b172b3f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.create_unique_constraint('uq_apple_id', ['apple_id'])
        batch_op.create_unique_constraint('uq_google_id', ['google_id'])
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')
        batch_op.drop_constraint('uq_google_id', type_='unique')
        batch_op.drop_constraint('uq_apple_id', type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
